services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
        - nginx
    restart: always
    networks:
      - clarusnet

  nginx:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: bridge
