# services:
#   gitea:
#     image: gitea/gitea:latest
#     environment:
#       - DB_TYPE=postgres
#       - DB_HOST=db:5432
#       - DB_NAME=gitea
#       - DB_USER=gitea
#       - DB_PASSWD=gitea
#     restart: always
#     volumes:
#       - git_data:/data
#     ports:
#       - 3000:3000
#   db:
#     image: postgres:alpine
#     environment:
#       - POSTGRES_USER=gitea
#       - POSTGRES_PASSWORD=gitea
#       - POSTGRES_DB=gitea
#     restart: always
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     expose:
#       - 5432
# volumes:
#   db_data:
#   git_data:
  
  
version: "2"

services:
  server:
    image: docker.gitea.com/gitea:1.23.5-rootless
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data